# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.

import json
import logging
import os
import shutil
from pathlib import Path
from typing import Any

from mcp.types import TextContent, Tool

from discopop_library.ProjectManager.configurations.execution import execute_configuration
from mcp_server.tools.helpers import ToolContext

logger = logging.getLogger("discopop-mcp")

TOOL = Tool(
    name="instrument_for_hotspot_detection",
    description=(
        "OPTIONAL STEP. Compile the project with hotspot detection instrumentation. "
        "Call this after set_compile_script and create_execution_configuration, "
        "and before run_hotspot_profiling. "
        "\n\n"
        "This tool runs compile.sh using hd_settings.json, which sets "
        "CC=discopop_hotspot_cc and CXX=discopop_hotspot_cxx and adds -fopenmp. "
        "The resulting binary measures per-loop and per-function execution times "
        "to identify hotspot regions. "
        "\n\n"
        "The overhead of the full hotspot profiling is much lower than the overhead "
        "incurred by the data dependency profiling (instrument_project / run_instrumented_binary). "
        "This makes it practical to run with somewhat larger inputs than would be "
        "feasible for data dependency profiling. However, inputs should still be "
        "small to medium sized with realistic but relatively short runtimes to keep "
        "the total profiling time manageable. "
        "\n\n"
        "IMPORTANT: If the project source code is modified after hotspot detection "
        "results have been collected, those results become stale and must be "
        "regenerated by re-running this tool and the subsequent hotspot steps. "
        "\n\n"
        "This tool deletes the entire .discopop/hotspot_detection/ directory before "
        "compiling to ensure no stale results from prior runs are mixed in. "
        "\n\n"
        "After this tool succeeds, call run_hotspot_profiling at least twice with "
        "different execution configurations to collect timing data from varied inputs. "
        "Then call run_hotspot_analysis to process the collected data."
    ),
    inputSchema={
        "type": "object",
        "properties": {
            "project_path": {
                "type": "string",
                "description": "Absolute path to the project root.",
            },
            "config_name": {
                "type": "string",
                "description": (
                    "Name of an existing execution configuration created via "
                    "create_execution_configuration. Required by the project manager "
                    "for environment setup."
                ),
            },
            "timeout_seconds": {
                "type": "integer",
                "description": ("Maximum time in seconds allowed for compilation. " "Default: 3600."),
            },
        },
        "required": ["project_path", "config_name"],
        "additionalProperties": False,
    },
)


def handle(arguments: dict[str, Any], ctx: ToolContext) -> list[TextContent]:
    try:
        project_path = arguments.get("project_path", "")
        config_name = arguments.get("config_name", "")
        timeout_seconds = arguments.get("timeout_seconds", 3600)

        p = Path(project_path)
        configs_dir = p / ".discopop" / "project" / "configs"
        compile_sh = configs_dir / "compile.sh"
        hd_settings = configs_dir / "hd_settings.json"
        hotspot_dir = p / ".discopop" / "hotspot_detection"

        if not compile_sh.exists():
            return ctx.error(f"compile.sh not found at {compile_sh}. Run set_compile_script first.")
        if not hd_settings.exists():
            return ctx.error("hd_settings.json not found. Run initialize_discopop_directory first.")
        config_dir = configs_dir / config_name
        if not config_dir.exists():
            return ctx.error(f"Configuration '{config_name}' not found. Run create_execution_configuration first.")

        if hotspot_dir.exists():
            shutil.rmtree(str(hotspot_dir))
            ctx.log_action(
                project_path,
                "instrument_for_hotspot_detection",
                "Deleted stale .discopop/hotspot_detection/ directory",
            )

        pm_args = ctx.make_pm_args(project_path, timeout_seconds)

        ctx.log_action(
            project_path,
            "instrument_for_hotspot_detection",
            f"Launching compile.sh via hd_settings (discopop_hotspot_cxx), config='{config_name}', timeout={timeout_seconds}s",
        )
        original_cwd = os.getcwd()
        try:
            exec_result = execute_configuration(
                arguments=pm_args,
                project_copy_root_path=project_path,
                config_path=str(config_dir),
                settings_path=str(hd_settings),
                script_path=str(compile_sh),
                thread_count=1,
                timeout=float(timeout_seconds),
            )
        finally:
            os.chdir(original_cwd)

        if exec_result is None:
            return ctx.error("execute_configuration returned None — hd_settings.json may be missing or malformed.")

        returncode, elapsed, stdout, stderr = exec_result

        if returncode != 0:
            result: dict[str, Any] = {
                "status": "error",
                "message": f"Hotspot detection compilation failed with return code {returncode}.",
                "returncode": returncode,
                "elapsed_time": elapsed,
                "stdout": stdout,
                "stderr": stderr,
            }
        else:
            ctx.log_action(
                project_path,
                "instrument_for_hotspot_detection",
                f"Compilation succeeded in {elapsed}s",
            )
            result = {
                "status": "success",
                "project_path": project_path,
                "returncode": returncode,
                "elapsed_time": elapsed,
                "stdout": stdout,
                "stderr": stderr,
            }

        ctx.log_response("instrument_for_hotspot_detection", result)
        return [TextContent(type="text", text=json.dumps(result))]

    except Exception as e:
        error_msg = f"Error during hotspot detection instrumentation: {str(e)}"
        logger.error(error_msg, exc_info=True)
        return [TextContent(type="text", text=json.dumps({"status": "error", "message": error_msg}))]
