# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.

name: "Check for DiscoPoP project tags"
on: [push, pull_request]

jobs:
  check-project-tags:
    runs-on: ubuntu-latest
    name: Check for DiscoPoP project tags
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: "Check all files for DiscoPoP License tag"
        run: |
          ERROR=""
          for FILE in $(find . -type f -not -path "**/.git/**" -not -path "**/test/**" -not -path "**/LICENSE" -not -path "./VERSION" -not -path "**/_version.py" -not -path "**.svg")
          do
            FILE_ERROR=""
            head -n 20 ${FILE} | grep -q "DiscoPoP software" || echo "Missing License tag at: ${FILE}" && FILE_ERROR="yes" && ERROR="yes"
            [ -z "$FILE_ERROR" ] || continue
            head -n 20 ${FILE} | grep -q "Technische Universitaet Darmstadt, Germany" || echo "Missing License tag at: ${FILE}" && FILE_ERROR="yes" && ERROR="yes"
            [ -z "$FILE_ERROR" ] || continue
            head -n 20 ${FILE} | grep -q "3-Clause BSD License" || echo "Missing License tag at: ${FILE}" && FILE_ERROR="yes" && ERROR="yes"
          done
          # Report error (1), if license tags are missing
          echo "ERROR: ${ERROR}"
          [ -z "$ERROR" ] || exit 1
          # else, finish without error
          exit 0