# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.

name: "Check for DiscoPoP project tags"
on: [push, pull_request]

jobs:
  check-project-tags:
    runs-on: ubuntu-latest
    name: Check for DiscoPoP project tags
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: "Check all files for DiscoPoP License tag"
        run: |
          for FILE in $(find .)
          do
            echo "Hello from: ${FILE}"
          done

        # head -n 20 setup.py | grep "DiscoPoP software\|Technische Universitaet Darmstadt, Germany\|3-Clause BSD License"