# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.

name: "Check for DiscoPoP project tags"
on: [push, pull_request]

jobs:
  check-project-tags:
    runs-on: ubuntu-latest
    name: Check for DiscoPoP project tags
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: "Check all files for DiscoPoP License tag"
        run: |
          ERROR_FILES=""
          for FILE in $(find . -type f -not -path "**/.git/**" -not -path "**/test/**")
          do
            ERROR=""
            head -n 20 ${FILE} | grep -q "DiscoPoP software" || ERROR="yes"
            head -n 20 ${FILE} | grep -q "Technische Universitaet Darmstadt, Germany" || ERROR="yes"
            head -n 20 ${FILE} | grep -q "3-Clause BSD License" || ERROR="yes"
            # add file to ERROR_FILES if the license tag is missing
            [ -z "$ERROR" ] && ERROR_FILES="${ERROR_FILES};${FILE}"
          done
          # Report missing license tags, if ERROR_FILES is not empty
          [ -z "$ERROR_FILES" ] && exit 0

          echo "Error files:\n${ERROR_FILES}" 
          exit 1