# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.

name: "DiscoPoP CI"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  setup_shared_dependencies:
    runs-on: self-hosted
    name: Setup shared dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # uses requirements.txt

      - name: Setup shared directory
        run: |
          mkdir -p ../shared/bin
          mkdir -p ../shared/third_party
          mkdir -p ../shared/build

      - name: Setup LLVM 11.1.0
        run: |
          CURDIR=$(pwd)
          echo "CURDIR: ${CURDIR}"
          if [ ! -d "../shared/third_party/llvm-11.1.0" ]; then
            echo "Downloading llvm 11.1.0"
            cd ../shared/third_party
            wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10.tar.xz
            tar -xvf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10.tar.xz
            mv clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10 llvm-11.1.0
            rm clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10.tar.xz
            cd ${CURDIR}
          fi

      - name: Setup Python venv
        run: |
          CURDIR=$(pwd)
          if [ ! -d "../shared/venv" ]; then
            cd ../shared
            python3 -m venv venv
            cd ${CURDIR}
          fi

      - name: Prepare PATH extension
        run: |
          if [ ! -d "../shared/PATH_extensions.txt" ]; then
            rm -f ../shared/PATH_extensions.txt
          fi

          echo -n "$(pwd)/../shared/third_party/llvm-11.1.0/bin" >> ../shared/PATH_extensions.txt

      - name: extend PATH
        run: |
          echo $PATH
          export PATH=$PATH:$(cat ../shared/PATH_extensions.txt)
          echo $PATH

  execute_code_checks:
    runs-on: self-hosted
    name: Execute Code Checks
    needs: setup_shared_dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: "Check all files for DiscoPoP License tag"
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          ./scripts/dev/check-license.sh $(find . -type f)

      - name: Install Python dependencies
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          pip install -r requirements.txt

      - name: "Run MyPy Type Checker - DiscoPoP Explorer"
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          python -m mypy --config-file=mypy.ini -p discopop_explorer

      - name: "Run MyPy Type Checker - DiscoPoP Library"
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          python -m mypy --config-file=mypy.ini -p discopop_library

      - name: "Check formatting of DiscoPoP Explorer"
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          python -m black -l 120 --check discopop_explorer

      - name: "Check formatting of DiscoPoP Library"
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          python -m black -l 120 --check discopop_library

  build_discopop_profiler:
    runs-on: self-hosted
    name: Build DiscoPoP
    needs: execute_code_checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          pip install -r requirements.txt

      - name: "CMake DiscoPoP profiler"
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          LLVM_PATH=$(pwd)/../shared/third_party/llvm-11.1.0
          VENV_PATH=$(pwd)/../shared/venv
          cd ../shared/build
          cmake \
           -DUSE_VENV=${VENV_PATH} \
           -DLLVM_DIST_PATH=${LLVM_PATH} \
           -DCMAKE_BUILD_TYPE=Debug \
           -DDP_CALLTREE_PROFILING=1 \
           ../../discopop

      - name: "Make DiscoPoP profiler"
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          cd ../shared/build
          make -j24

      - name: "Make DiscoPoP Python modules"
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          cd ../shared/build
          make install_python_modules

  execute_cxx_unit_tests:
    runs-on: self-hosted
    name: Execute C++ unit tests
    needs: build_discopop_profiler
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: C++ unit tests
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          ../shared/build/test/unit_tests/DiscoPoP_UT

  execute_end_to_end_tests:
    runs-on: self-hosted
    name: Execute end-to-end tests
    needs: build_discopop_profiler
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Python end-to-end-tests
        run: |
          export PATH=$(cat ../shared/PATH_extensions.txt):$PATH
          . ../shared/venv/bin/activate
          python -m unittest -v -k *.end_to_end.*
