# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.

name: "DiscoPoP CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
# used for eventual multiple operating system testing
  create_matrix:
    runs-on: self-hosted
    name: Create matrix
    outputs:
      matrix: ${{ steps.create_matrix.outputs.matrix }}
    steps:
      - name: Create build matrix
        id: create_matrix
        shell: bash
        run: |
          matrix='{"include":[
            {"id":"ubuntu-24-04",
             "base_image":"ubuntu:24.04",
             "install_deps_cmd":" export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y python3 python3-pip python3-venv python3-tk build-essential make cmake git llvm-19-dev clang-19 libomp-19-dev libboost-all-dev"
            },
            {"id":"ubuntu-22-04",
             "base_image":"ubuntu:22.04",
             "install_deps_cmd":" export DEBIAN_FRONTEND=noninteractive && deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main && deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy main && apt update && apt install -y python3 python3-pip python3-venv python3-tk build-essential make cmake git llvm-19-dev clang-19 libomp-19-dev libboost-all-dev"
            }
          ]}'

          if [[ "${{ github.event_name }}" = "pull_request" && "${{ github.base_ref }}" != "master" ]]; then
            matrix='{"include":[
              {"id":"ubuntu-24-04",
              "base_image":"ubuntu:24.04",
              "install_deps_cmd":"export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y python3 python3-pip python3-venv python3-tk build-essential make cmake git llvm-19-dev clang-19 libomp-19-dev libboost-all-dev"
              },
              {"id":"ubuntu-22-04",
              "base_image":"ubuntu:22.04",
              "install_deps_cmd":"export DEBIAN_FRONTEND=noninteractive && deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main && deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy main && apt update && apt install -y python3 python3-pip python3-venv python3-tk build-essential make cmake git llvm-19-dev clang-19 libomp-19-dev libboost-all-dev"
              },
            ]}'
          fi

          {
            echo "matrix<<END"
            echo "$matrix"
            echo "END"
          } >> "$GITHUB_OUTPUT"


  build_install_and_test:
    runs-on: self-hosted
    container:
      image: ${{ matrix.base_image }}
    name: "Build image, install package & test for: (${{ matrix.id }}) with image: (${{ matrix.base_image }})"
    needs: [create_matrix]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.create_matrix.outputs.matrix) }}

    steps:
      - name: Install Prerequisites
        run: |
          ${{ matrix.install_deps_cmd}}

      - name: Checkout Repository
        uses: actions/checkout@v3
#        with:
#          submodules: recursive

      - name: Check all files for DiscoPoP License tag
        run: |
          ./scripts/dev/check-license.sh $(find . -type f)

      - name: Setup venv and install DiscoPoP
        run: |
          python3 -m venv venv
          venv/bin/pip install -e . ./profiler ./explorer ./library

      - name: Run MyPy Type Checking
        run: |
            venv/bin/python3 -m mypy --config-file=mypy.ini

      - name: Check formatting of DiscoPoP Explorer
        run: |
            venv/bin/python3 -m black -l 120 --check explorer

      - name: Check formatting of DiscoPoP Library
        run: |
            venv/bin/python3 -m black -l 120 --check library

 #     - name: Execute C++ unit tests
 #       run: |
 #         docker run --rm discopop_ci_${{ github.sha }}-${{ matrix.id }} \
 #           build/test/unit_tests/DiscoPoP_UT

      - name: Profiler gold standard tests
        run: |
            . venv/bin/activate
            python3 -m unittest -v -k "*test.profiler.*"

      - name: Python end-to-end-tests
        run: |
            . venv/bin/activate
            python3 -m unittest -v -k "*.end_to_end.*"



  checks_successful:
    runs-on: self-hosted
    name: Checks successful
    needs: [build_install_and_test]
    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    steps:
      - name: Report
        run: |
          echo "All checks successful!"
