# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.

ARG BASE_IMAGE="ubuntu:24.04"
FROM ${BASE_IMAGE}

ARG PACKAGE_FILE

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /usr/local/ci

RUN apt-get update && apt-get install -y \
    ca-certificates \
    apt-utils

COPY packages/${PACKAGE_FILE} /tmp/${PACKAGE_FILE}

RUN apt-get install -y /tmp/${PACKAGE_FILE}

ENV PATH="/opt/DiscoPoP/venv/bin:${PATH}"

WORKDIR /opt/DiscoPoP