# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.
ARG BASE_IMAGE_TAG=""

FROM discopop_ci_base${BASE_IMAGE_TAG}
WORKDIR /usr/local/ci

# import repository to /usr/local/ci/discopop
# Dockerfile located in discopop/.github/workflows, hence the ../..
ADD ../.. /usr/local/ci/discopop

# build discopop
RUN cmake -S discopop -B discopop/build -DCMAKE_BUILD_TYPE=Debug -DUSE_VENV=/usr/local/ci/venv -DDP_CALLTREE_PROFILING=1 -DDP_BUILD_UNITTESTS=1
RUN make --directory=discopop/build -j
RUN make --directory=discopop/build install_python_modules

WORKDIR /usr/local/ci/discopop

RUN /usr/local/ci/venv/bin/pip install -r requirements.txt

RUN ln -s /usr/local/ci/discopop/build/scripts/CC_wrapper.sh /usr/local/bin/discopop_cc
RUN ln -s /usr/local/ci/discopop/build/scripts/CXX_wrapper.sh /usr/local/bin/discopop_cxx
