# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.
FROM discopop_ci_base
WORKDIR /usr/local/ci

# import repository to /usr/local/ci/discopop
# Dockerfile located in discopop/.github/workflows, hence the ../..
ADD ../.. /usr/local/ci/discopop

# build discopop
RUN cmake -S discopop -B discopop/build -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIST_PATH=/usr/local/ci/software/llvm-11.1.0 -DUSE_VENV=/usr/local/ci/venv -DDP_CALLTREE_PROFILING=1
RUN make --directory=discopop/build -j
RUN make --directory=discopop/build install_python_modules

WORKDIR /usr/local/ci/discopop

RUN /usr/local/ci/venv/bin/pip install -r requirements.txt
