# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.

name: Publish discopop-explorer to PyPI

on:
  push:
    tags:
      - "explorer_v*"

permissions:
  contents: read
  # IMPORTANT: this permission is mandatory for Trusted Publishing
  id-token: write

jobs:
  publish:
    name: Build and publish discopop-explorer
    runs-on: ubuntu-22.04
    environment: pypi


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Build discopop-explorer
        run: pip install build && python -m build explorer/

      - name: Publish discopop-explorer to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: explorer/dist/
